//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.2
//     from Assets/Scripts/PlayerControlRootScripts/PlayerControlls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControlls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControlls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControlls"",
    ""maps"": [
        {
            ""name"": ""Basic"",
            ""id"": ""d7fe1f4c-4285-4a34-8013-8742b0a3d54a"",
            ""actions"": [
                {
                    ""name"": ""MoveLeft"",
                    ""type"": ""Button"",
                    ""id"": ""31ae585b-847a-440b-86ae-87fc9a0c6675"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MoveRight"",
                    ""type"": ""Button"",
                    ""id"": ""3c8caa9d-d74c-4637-b40f-648d4ea9679a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""117e4740-2526-44ab-8f33-ab5ba1dcc00a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DiveLeft"",
                    ""type"": ""Button"",
                    ""id"": ""945bca19-7fdf-4580-bd01-ea3f922ee90c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DiveRight"",
                    ""type"": ""Button"",
                    ""id"": ""11912025-1963-43aa-aaa3-e0ec7fdc9649"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""b2a348ef-e6e2-43b6-9a34-e8dc6829395b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionOne"",
                    ""type"": ""Button"",
                    ""id"": ""c3a8b27d-c209-4516-83f7-ec3aae3eecb6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionTwo"",
                    ""type"": ""Button"",
                    ""id"": ""0d406080-747d-4852-ad99-18c6a868ce13"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""c8c317bc-ef47-4746-9137-2a0d8a66e95a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChargeOne"",
                    ""type"": ""Button"",
                    ""id"": ""8f80c85d-2099-45ed-9413-93aa42b2fff1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChargeTwo"",
                    ""type"": ""Button"",
                    ""id"": ""23debf72-b815-4b58-9b1f-e0d50ce5e3ab"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CursorUp"",
                    ""type"": ""Button"",
                    ""id"": ""bef741ed-2d1e-4d57-a540-00b84949f509"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CursorDown"",
                    ""type"": ""Button"",
                    ""id"": ""4579d65a-f2df-4083-bc36-6d9c886374cf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AimUp"",
                    ""type"": ""Button"",
                    ""id"": ""6477a45c-ab48-4a77-a02d-75ad1ec3faf4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""AimDown"",
                    ""type"": ""Button"",
                    ""id"": ""7fdbb9dc-df14-48b3-b00f-2426f42e6360"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AimLeft"",
                    ""type"": ""Button"",
                    ""id"": ""a3bc9969-233b-497a-8a2d-f63a31792df9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AimRight"",
                    ""type"": ""Button"",
                    ""id"": ""8f32df3e-ab50-439b-a547-a935a9d85006"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8dea9cde-5bc0-4b3a-90c7-459bc63ddcc0"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6bd542b8-4f3e-4482-8c9a-16f217c73eba"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""KeyboardDiveLeft"",
                    ""id"": ""001d675f-9694-4d29-8dca-2c5e0cfe7949"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DiveLeft"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""ba3b6d7e-b78a-45a5-8cf2-16cad11f2ef6"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DiveLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""d0e8f1e0-9445-473a-903d-de35f5ee29f6"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DiveLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""GampadDiveLeft"",
                    ""id"": ""e57c42d1-4a91-4285-ab86-754bfb86d4e8"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DiveLeft"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""8f63ca6b-0519-468f-8422-ab48f036a171"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DiveLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""f5ae4084-83cd-4ee9-9ad4-04548353fdc8"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DiveLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""KeyboardDiveRight"",
                    ""id"": ""91775af3-a2c1-4613-a601-e1cb3a05a5a6"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DiveRight"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""46ad43be-843c-4251-aa1c-ba242f4af3d4"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DiveRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""28433814-5358-4903-9509-3b2c72dda3f0"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DiveRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""GamepadDiveRight"",
                    ""id"": ""77bb94f1-f598-4c9e-a967-d12adbc1fadc"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DiveRight"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""eda17a7d-baad-4286-8cc5-a6488828f072"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DiveRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""bb36f0ca-f038-4dce-b021-850d5fcf4d67"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DiveRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""693f075f-c16a-4e71-ab4f-16c4e8c676c3"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3dd9056b-4077-4fae-8e89-e8948491ceec"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2be340f6-3adf-4d45-ba71-6aeef82d9bba"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActionOne"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c7c0f966-6d54-45ef-b691-0519e30b894f"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActionOne"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""59e64cbe-74bf-40a5-b3a2-8f5ad39deb71"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActionTwo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8125b52c-431b-4dda-b36a-e75f3b505d6c"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActionTwo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0da99045-dbc3-470b-a8a1-9e2b7a184476"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7feadca7-928c-4077-8ac7-7777dd304846"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4e4505a2-ae8c-4083-9ad3-e228e16dbba5"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChargeOne"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9557fd74-4a56-4819-b32a-c1375538c2e0"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChargeOne"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f1a9af5-20d9-4ae5-bc29-b6a39729fad5"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChargeTwo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1cb05b45-8bf7-4614-a7b3-4acd789bca65"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChargeTwo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a13f2fe0-25a4-43fe-843f-2f7a37131fe9"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a3b83905-ad11-4d25-b814-f672c8ff9467"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""323e27f2-522e-4e19-a148-5a048aeddb65"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dc5afc40-31da-40c4-981f-e88eba613cae"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4ae11b63-bb25-4194-86bd-20992fc9abc4"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CursorUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""898e6657-169b-4020-bf31-6dfe6e85ba28"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CursorDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3256e10d-9b19-4e65-9bb7-216ff24170f1"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AimUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b3a9753-28c9-49b9-bb15-ff9b5d2c877d"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AimDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""02555ee5-4cf3-4655-8c68-35e6de767bac"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AimLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""538e3a92-6a6b-4eeb-8a09-3e9f4f306138"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AimRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Basic
        m_Basic = asset.FindActionMap("Basic", throwIfNotFound: true);
        m_Basic_MoveLeft = m_Basic.FindAction("MoveLeft", throwIfNotFound: true);
        m_Basic_MoveRight = m_Basic.FindAction("MoveRight", throwIfNotFound: true);
        m_Basic_Jump = m_Basic.FindAction("Jump", throwIfNotFound: true);
        m_Basic_DiveLeft = m_Basic.FindAction("DiveLeft", throwIfNotFound: true);
        m_Basic_DiveRight = m_Basic.FindAction("DiveRight", throwIfNotFound: true);
        m_Basic_Shoot = m_Basic.FindAction("Shoot", throwIfNotFound: true);
        m_Basic_ActionOne = m_Basic.FindAction("ActionOne", throwIfNotFound: true);
        m_Basic_ActionTwo = m_Basic.FindAction("ActionTwo", throwIfNotFound: true);
        m_Basic_Pause = m_Basic.FindAction("Pause", throwIfNotFound: true);
        m_Basic_ChargeOne = m_Basic.FindAction("ChargeOne", throwIfNotFound: true);
        m_Basic_ChargeTwo = m_Basic.FindAction("ChargeTwo", throwIfNotFound: true);
        m_Basic_CursorUp = m_Basic.FindAction("CursorUp", throwIfNotFound: true);
        m_Basic_CursorDown = m_Basic.FindAction("CursorDown", throwIfNotFound: true);
        m_Basic_AimUp = m_Basic.FindAction("AimUp", throwIfNotFound: true);
        m_Basic_AimDown = m_Basic.FindAction("AimDown", throwIfNotFound: true);
        m_Basic_AimLeft = m_Basic.FindAction("AimLeft", throwIfNotFound: true);
        m_Basic_AimRight = m_Basic.FindAction("AimRight", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Basic
    private readonly InputActionMap m_Basic;
    private IBasicActions m_BasicActionsCallbackInterface;
    private readonly InputAction m_Basic_MoveLeft;
    private readonly InputAction m_Basic_MoveRight;
    private readonly InputAction m_Basic_Jump;
    private readonly InputAction m_Basic_DiveLeft;
    private readonly InputAction m_Basic_DiveRight;
    private readonly InputAction m_Basic_Shoot;
    private readonly InputAction m_Basic_ActionOne;
    private readonly InputAction m_Basic_ActionTwo;
    private readonly InputAction m_Basic_Pause;
    private readonly InputAction m_Basic_ChargeOne;
    private readonly InputAction m_Basic_ChargeTwo;
    private readonly InputAction m_Basic_CursorUp;
    private readonly InputAction m_Basic_CursorDown;
    private readonly InputAction m_Basic_AimUp;
    private readonly InputAction m_Basic_AimDown;
    private readonly InputAction m_Basic_AimLeft;
    private readonly InputAction m_Basic_AimRight;
    public struct BasicActions
    {
        private @PlayerControlls m_Wrapper;
        public BasicActions(@PlayerControlls wrapper) { m_Wrapper = wrapper; }
        public InputAction @MoveLeft => m_Wrapper.m_Basic_MoveLeft;
        public InputAction @MoveRight => m_Wrapper.m_Basic_MoveRight;
        public InputAction @Jump => m_Wrapper.m_Basic_Jump;
        public InputAction @DiveLeft => m_Wrapper.m_Basic_DiveLeft;
        public InputAction @DiveRight => m_Wrapper.m_Basic_DiveRight;
        public InputAction @Shoot => m_Wrapper.m_Basic_Shoot;
        public InputAction @ActionOne => m_Wrapper.m_Basic_ActionOne;
        public InputAction @ActionTwo => m_Wrapper.m_Basic_ActionTwo;
        public InputAction @Pause => m_Wrapper.m_Basic_Pause;
        public InputAction @ChargeOne => m_Wrapper.m_Basic_ChargeOne;
        public InputAction @ChargeTwo => m_Wrapper.m_Basic_ChargeTwo;
        public InputAction @CursorUp => m_Wrapper.m_Basic_CursorUp;
        public InputAction @CursorDown => m_Wrapper.m_Basic_CursorDown;
        public InputAction @AimUp => m_Wrapper.m_Basic_AimUp;
        public InputAction @AimDown => m_Wrapper.m_Basic_AimDown;
        public InputAction @AimLeft => m_Wrapper.m_Basic_AimLeft;
        public InputAction @AimRight => m_Wrapper.m_Basic_AimRight;
        public InputActionMap Get() { return m_Wrapper.m_Basic; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BasicActions set) { return set.Get(); }
        public void SetCallbacks(IBasicActions instance)
        {
            if (m_Wrapper.m_BasicActionsCallbackInterface != null)
            {
                @MoveLeft.started -= m_Wrapper.m_BasicActionsCallbackInterface.OnMoveLeft;
                @MoveLeft.performed -= m_Wrapper.m_BasicActionsCallbackInterface.OnMoveLeft;
                @MoveLeft.canceled -= m_Wrapper.m_BasicActionsCallbackInterface.OnMoveLeft;
                @MoveRight.started -= m_Wrapper.m_BasicActionsCallbackInterface.OnMoveRight;
                @MoveRight.performed -= m_Wrapper.m_BasicActionsCallbackInterface.OnMoveRight;
                @MoveRight.canceled -= m_Wrapper.m_BasicActionsCallbackInterface.OnMoveRight;
                @Jump.started -= m_Wrapper.m_BasicActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_BasicActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_BasicActionsCallbackInterface.OnJump;
                @DiveLeft.started -= m_Wrapper.m_BasicActionsCallbackInterface.OnDiveLeft;
                @DiveLeft.performed -= m_Wrapper.m_BasicActionsCallbackInterface.OnDiveLeft;
                @DiveLeft.canceled -= m_Wrapper.m_BasicActionsCallbackInterface.OnDiveLeft;
                @DiveRight.started -= m_Wrapper.m_BasicActionsCallbackInterface.OnDiveRight;
                @DiveRight.performed -= m_Wrapper.m_BasicActionsCallbackInterface.OnDiveRight;
                @DiveRight.canceled -= m_Wrapper.m_BasicActionsCallbackInterface.OnDiveRight;
                @Shoot.started -= m_Wrapper.m_BasicActionsCallbackInterface.OnShoot;
                @Shoot.performed -= m_Wrapper.m_BasicActionsCallbackInterface.OnShoot;
                @Shoot.canceled -= m_Wrapper.m_BasicActionsCallbackInterface.OnShoot;
                @ActionOne.started -= m_Wrapper.m_BasicActionsCallbackInterface.OnActionOne;
                @ActionOne.performed -= m_Wrapper.m_BasicActionsCallbackInterface.OnActionOne;
                @ActionOne.canceled -= m_Wrapper.m_BasicActionsCallbackInterface.OnActionOne;
                @ActionTwo.started -= m_Wrapper.m_BasicActionsCallbackInterface.OnActionTwo;
                @ActionTwo.performed -= m_Wrapper.m_BasicActionsCallbackInterface.OnActionTwo;
                @ActionTwo.canceled -= m_Wrapper.m_BasicActionsCallbackInterface.OnActionTwo;
                @Pause.started -= m_Wrapper.m_BasicActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_BasicActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_BasicActionsCallbackInterface.OnPause;
                @ChargeOne.started -= m_Wrapper.m_BasicActionsCallbackInterface.OnChargeOne;
                @ChargeOne.performed -= m_Wrapper.m_BasicActionsCallbackInterface.OnChargeOne;
                @ChargeOne.canceled -= m_Wrapper.m_BasicActionsCallbackInterface.OnChargeOne;
                @ChargeTwo.started -= m_Wrapper.m_BasicActionsCallbackInterface.OnChargeTwo;
                @ChargeTwo.performed -= m_Wrapper.m_BasicActionsCallbackInterface.OnChargeTwo;
                @ChargeTwo.canceled -= m_Wrapper.m_BasicActionsCallbackInterface.OnChargeTwo;
                @CursorUp.started -= m_Wrapper.m_BasicActionsCallbackInterface.OnCursorUp;
                @CursorUp.performed -= m_Wrapper.m_BasicActionsCallbackInterface.OnCursorUp;
                @CursorUp.canceled -= m_Wrapper.m_BasicActionsCallbackInterface.OnCursorUp;
                @CursorDown.started -= m_Wrapper.m_BasicActionsCallbackInterface.OnCursorDown;
                @CursorDown.performed -= m_Wrapper.m_BasicActionsCallbackInterface.OnCursorDown;
                @CursorDown.canceled -= m_Wrapper.m_BasicActionsCallbackInterface.OnCursorDown;
                @AimUp.started -= m_Wrapper.m_BasicActionsCallbackInterface.OnAimUp;
                @AimUp.performed -= m_Wrapper.m_BasicActionsCallbackInterface.OnAimUp;
                @AimUp.canceled -= m_Wrapper.m_BasicActionsCallbackInterface.OnAimUp;
                @AimDown.started -= m_Wrapper.m_BasicActionsCallbackInterface.OnAimDown;
                @AimDown.performed -= m_Wrapper.m_BasicActionsCallbackInterface.OnAimDown;
                @AimDown.canceled -= m_Wrapper.m_BasicActionsCallbackInterface.OnAimDown;
                @AimLeft.started -= m_Wrapper.m_BasicActionsCallbackInterface.OnAimLeft;
                @AimLeft.performed -= m_Wrapper.m_BasicActionsCallbackInterface.OnAimLeft;
                @AimLeft.canceled -= m_Wrapper.m_BasicActionsCallbackInterface.OnAimLeft;
                @AimRight.started -= m_Wrapper.m_BasicActionsCallbackInterface.OnAimRight;
                @AimRight.performed -= m_Wrapper.m_BasicActionsCallbackInterface.OnAimRight;
                @AimRight.canceled -= m_Wrapper.m_BasicActionsCallbackInterface.OnAimRight;
            }
            m_Wrapper.m_BasicActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MoveLeft.started += instance.OnMoveLeft;
                @MoveLeft.performed += instance.OnMoveLeft;
                @MoveLeft.canceled += instance.OnMoveLeft;
                @MoveRight.started += instance.OnMoveRight;
                @MoveRight.performed += instance.OnMoveRight;
                @MoveRight.canceled += instance.OnMoveRight;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @DiveLeft.started += instance.OnDiveLeft;
                @DiveLeft.performed += instance.OnDiveLeft;
                @DiveLeft.canceled += instance.OnDiveLeft;
                @DiveRight.started += instance.OnDiveRight;
                @DiveRight.performed += instance.OnDiveRight;
                @DiveRight.canceled += instance.OnDiveRight;
                @Shoot.started += instance.OnShoot;
                @Shoot.performed += instance.OnShoot;
                @Shoot.canceled += instance.OnShoot;
                @ActionOne.started += instance.OnActionOne;
                @ActionOne.performed += instance.OnActionOne;
                @ActionOne.canceled += instance.OnActionOne;
                @ActionTwo.started += instance.OnActionTwo;
                @ActionTwo.performed += instance.OnActionTwo;
                @ActionTwo.canceled += instance.OnActionTwo;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
                @ChargeOne.started += instance.OnChargeOne;
                @ChargeOne.performed += instance.OnChargeOne;
                @ChargeOne.canceled += instance.OnChargeOne;
                @ChargeTwo.started += instance.OnChargeTwo;
                @ChargeTwo.performed += instance.OnChargeTwo;
                @ChargeTwo.canceled += instance.OnChargeTwo;
                @CursorUp.started += instance.OnCursorUp;
                @CursorUp.performed += instance.OnCursorUp;
                @CursorUp.canceled += instance.OnCursorUp;
                @CursorDown.started += instance.OnCursorDown;
                @CursorDown.performed += instance.OnCursorDown;
                @CursorDown.canceled += instance.OnCursorDown;
                @AimUp.started += instance.OnAimUp;
                @AimUp.performed += instance.OnAimUp;
                @AimUp.canceled += instance.OnAimUp;
                @AimDown.started += instance.OnAimDown;
                @AimDown.performed += instance.OnAimDown;
                @AimDown.canceled += instance.OnAimDown;
                @AimLeft.started += instance.OnAimLeft;
                @AimLeft.performed += instance.OnAimLeft;
                @AimLeft.canceled += instance.OnAimLeft;
                @AimRight.started += instance.OnAimRight;
                @AimRight.performed += instance.OnAimRight;
                @AimRight.canceled += instance.OnAimRight;
            }
        }
    }
    public BasicActions @Basic => new BasicActions(this);
    public interface IBasicActions
    {
        void OnMoveLeft(InputAction.CallbackContext context);
        void OnMoveRight(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnDiveLeft(InputAction.CallbackContext context);
        void OnDiveRight(InputAction.CallbackContext context);
        void OnShoot(InputAction.CallbackContext context);
        void OnActionOne(InputAction.CallbackContext context);
        void OnActionTwo(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnChargeOne(InputAction.CallbackContext context);
        void OnChargeTwo(InputAction.CallbackContext context);
        void OnCursorUp(InputAction.CallbackContext context);
        void OnCursorDown(InputAction.CallbackContext context);
        void OnAimUp(InputAction.CallbackContext context);
        void OnAimDown(InputAction.CallbackContext context);
        void OnAimLeft(InputAction.CallbackContext context);
        void OnAimRight(InputAction.CallbackContext context);
    }
}
